Add additional antigen and sera attributes
acorg/Racmacs pull request #109
Opened 2022-03-12 14:20 UTC by drserajames

Add antigen and sera attributes: `agLineage()`, `srLineage()`, `agReassortant()`, `srReassortant()`, `agStrings()`, `srStrings()`, `agContinent()`, `agNucleotideSequences()`, `srNucleotideSequences()`

2022-03-12 16:16 UTC, shwilks requested changes
Looks great! Just missing tests for getting and setting nucleotide sequences, which would also pick up on the typo in the function name. 👍

2022-03-12 16:16 UTC, shwilks commented on R/map_props_points_antigens.R
> +`agNucelotideSequences<-` <- function(map, value) {
typo here I think?

2022-03-12 19:40 UTC, drserajames commented on R/map_props_points_antigens.R
> +`agNucelotideSequences<-` <- function(map, value) {
I couldn't find the agSequences tests, but I see them now, so I will add them there.

2022-03-14 09:23 UTC, shwilks approved these changes

2022-03-14 09:23 UTC, merged

2022-03-14 10:16 UTC, drserajames commented
Oh no! I forgot the documentation? Can I keep the version number the same & send another pull request?