Added some text to making-a-map-from-scratch.Rmd
acorg/Racmacs pull request #59
Opened 2021-05-23 14:19 UTC by bamueh

2021-05-23 14:21 UTC, bamueh commented
Hi Sam,

I had a go at adding some of the code snippets that you sent earlier this week to `making-a-map-from-scratch.Rmd`. I'm not sure everything is in the right format to compile, so I'm happy to talk about this more.

Cheers,
Barbara

2021-05-27 14:45 UTC, shwilks commented
Sorry for the slow response Barbara, basically yeah, this looks great and is the right way to do it.  There are some small issues with the code though that I'll highlight.

2021-05-27 14:49 UTC, shwilks requested changes

2021-05-27 14:49 UTC, shwilks commented on vignettes/making-a-map-from-scratch.Rmd
> +srNames(map) <- c(colnames(titer_table))
you don't need the `c()` wrapper here

2021-05-27 14:49 UTC, shwilks commented on vignettes/making-a-map-from-scratch.Rmd
> +oldMap <- read.acmap("extdata/h3map2004_bootstrap.ace")
This causes the code to fail for me since it can't find "extdata/h3map2004_bootstrap.ace" in RStudio there is a button to attempt to knit the .rmd file to an html vignette, this is what fails for me so it might be worth making sure you can knit it ok after making changes

2021-05-31 08:07 UTC, bamueh commented on vignettes/making-a-map-from-scratch.Rmd
> +srNames(map) <- c(colnames(titer_table))
Thanks!

2021-05-31 08:11 UTC, bamueh commented on vignettes/making-a-map-from-scratch.Rmd
> +oldMap <- read.acmap("extdata/h3map2004_bootstrap.ace")
Hmm. It fails for me too. But how come it can find `extdata/h3map2004_hitable.csv` (line 40) but not `extdata/h3map2004_bootstrap.ace` even though they're in the same directory?

2021-06-02 14:09 UTC, shwilks commented on vignettes/making-a-map-from-scratch.Rmd
> +oldMap <- read.acmap("extdata/h3map2004_bootstrap.ace")
ah, yes for it to work you need to wrap it in the `system.file()` function like the other reference, then it should convert it to the appropriate path to the installed library

2023-11-23 12:52 UTC, closed without merging